//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPortalEntities : DbContext
    {
        public EPortalEntities()
            : base("name=EPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicantTest> ApplicantTests { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<EMailConfiguration> EMailConfigurations { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<GroupUserApplicant> GroupUserApplicants { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModulePage> ModulePages { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OrganizationPage> OrganizationPages { get; set; }
        public virtual DbSet<OrgEvent> OrgEvents { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Previleage> Previleages { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionAnswar> QuestionAnswars { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<Questionsource> Questionsources { get; set; }
        public virtual DbSet<QuestionsourceGroup> QuestionsourceGroups { get; set; }
        public virtual DbSet<QuestionType> QuestionTypes { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestInstruction> TestInstructions { get; set; }
        public virtual DbSet<TestQuestion> TestQuestions { get; set; }
        public virtual DbSet<TestSection> TestSections { get; set; }
        public virtual DbSet<UserAnswer> UserAnswers { get; set; }
        public virtual DbSet<UserAnswerMark> UserAnswerMarks { get; set; }
        public virtual DbSet<UserFeedBack> UserFeedBacks { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserMark> UserMarks { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserTestTIme> UserTestTImes { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
    }
}
