//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupUser()
        {
            this.GroupUserApplicants = new HashSet<GroupUserApplicant>();
        }
    
        public string Id { get; set; }
        public string GroupUserCode { get; set; }
        public string GroupUserName { get; set; }
        public string OganizationId { get; set; }
        public System.DateTime createdDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupUserApplicant> GroupUserApplicants { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
