//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUserApplicant
    {
        public string Id { get; set; }
        public string GroupUserId { get; set; }
        public string ApplicantId { get; set; }
        public string OganizationId { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual GroupUser GroupUser { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
