//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePage
    {
        public string Id { get; set; }
        public string ModuleId { get; set; }
        public string PageId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Page Page { get; set; }
    }
}
