//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgEvent
    {
        public string Id { get; set; }
        public string EventCode { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<bool> EventType { get; set; }
        public string EventDescription { get; set; }
        public string OganizationId { get; set; }
        public string Periodid { get; set; }
    }
}
