//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Previleage
    {
        public string Id { get; set; }
        public string RoleId { get; set; }
        public string PageId { get; set; }
        public string OperationId { get; set; }
        public string OrganizationID { get; set; }
        public bool RowState { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public Nullable<bool> PCreate { get; set; }
        public Nullable<bool> PUpdate { get; set; }
        public Nullable<bool> PDelete { get; set; }
        public Nullable<bool> PView { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Page Page { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
