//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectDetail
    {
        public string Id { get; set; }
        public string SubjectId { get; set; }
        public string CourseId { get; set; }
        public string OrganizationID { get; set; }
        public bool RowState { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
